"""add transaction orm

Revision ID: 333413784d96
Revises: c67534194872
Create Date: 2025-11-20 21:53:15.546193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '333413784d96'
down_revision: Union[str, Sequence[str], None] = 'c67534194872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('trans_id', sa.String(length=18), nullable=False),
    sa.Column('trans_dt', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('trans_id')
    )
    op.alter_column('currency', 'cur_dt',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency', 'cur_dt',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_table('transaction')
    # ### end Alembic commands ###
