"""Add Property and Private Ownership Table

Revision ID: 5e077ee666b0
Revises: 5fdcba90f616
Create Date: 2025-11-13 00:21:47.874449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy import Integer
from src.app.model.enums import CurType
from src.app.model.enums import PropertyType

# revision identifiers, used by Alembic.
revision: str = '5e077ee666b0'
down_revision: Union[str, Sequence[str], None] = '5fdcba90f616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('prop_id', sa.String(length=18), nullable=False),
    sa.Column('symbol', sa.String(length=35), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency', sqlalchemy_utils.ChoiceType(CurType, impl = Integer()), nullable=False),
    sa.Column('prop_type', sqlalchemy_utils.ChoiceType(PropertyType, impl = Integer()), nullable=False),
    sa.Column('is_public', sa.Boolean(create_constraint=True), nullable=False),
    sa.PrimaryKeyConstraint('prop_id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('private_prop_ownership',
    sa.Column('ownership_id', sa.String(length=18), nullable=False),
    sa.Column('prop_id', sa.String(length=18), nullable=False),
    sa.Column('user_id', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['prop_id'], ['property.prop_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ownership_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('private_prop_ownership')
    op.drop_table('property')
    # ### end Alembic commands ###
