"""Add FX table

Revision ID: 5fdcba90f616
Revises: 320b956e66ef
Create Date: 2025-11-07 23:54:11.476452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy import Integer
from src.app.model.enums import CurType

# revision identifiers, used by Alembic.
revision: str = '5fdcba90f616'
down_revision: Union[str, Sequence[str], None] = '320b956e66ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('currency', sqlalchemy_utils.ChoiceType(CurType, impl = Integer()), nullable=False),
    sa.Column('cur_dt', sa.Date(), nullable=False),
    sa.Column('rate', sa.DECIMAL(precision=15, scale=5, asdecimal=False), nullable=False),
    sa.PrimaryKeyConstraint('currency', 'cur_dt')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency')
    # ### end Alembic commands ###
