"""add description to property

Revision ID: 6211461fb14a
Revises: ca933ca9e956
Create Date: 2025-11-14 00:44:33.354453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6211461fb14a'
down_revision: Union[str, Sequence[str], None] = 'ca933ca9e956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'description')
    # ### end Alembic commands ###
