"""add user id

Revision ID: 85dff55dfb95
Revises: 9309e58f226a
Create Date: 2025-11-20 22:14:54.374801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85dff55dfb95'
down_revision: Union[str, Sequence[str], None] = '9309e58f226a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leg', sa.Column('user_id', sa.String(length=15), nullable=False))
    op.create_index('idx_leg_user_id', 'leg', ['user_id'], unique=False)
    op.create_foreign_key(None, 'leg', 'users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.add_column('transaction', sa.Column('user_id', sa.String(length=15), nullable=False))
    op.create_foreign_key(None, 'transaction', 'users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'user_id')
    op.drop_constraint(None, 'leg', type_='foreignkey')
    op.drop_index('idx_leg_user_id', table_name='leg')
    op.drop_column('leg', 'user_id')
    # ### end Alembic commands ###
