"""add account and leg

Revision ID: 9309e58f226a
Revises: 333413784d96
Create Date: 2025-11-20 22:00:58.641031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy import Integer
from src.app.model.enums import PlanType, LegType

# revision identifiers, used by Alembic.
revision: str = '9309e58f226a'
down_revision: Union[str, Sequence[str], None] = '333413784d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('acct_id', sa.String(length=18), nullable=False),
    sa.Column('user_id', sa.String(length=15), nullable=False),
    sa.Column('acct_name', sa.String(length=100), nullable=False),
    sa.Column('plan_type', sqlalchemy_utils.ChoiceType(PlanType, impl = Integer()), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('acct_id')
    )
    op.create_table('leg',
    sa.Column('leg_id', sa.String(length=18), nullable=False),
    sa.Column('trans_id', sa.String(length=18), nullable=False),
    sa.Column('leg_type', sqlalchemy_utils.ChoiceType(LegType, impl = Integer()), nullable=False),
    sa.Column('acct_id', sa.String(length=18), nullable=False),
    sa.Column('prop_id', sa.String(length=18), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=15, scale=5, asdecimal=False), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=15, scale=5, asdecimal=False), nullable=False),
    sa.ForeignKeyConstraint(['acct_id'], ['account.acct_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prop_id'], ['property.prop_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trans_id'], ['transaction.trans_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('leg_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leg')
    op.drop_table('account')
    # ### end Alembic commands ###
