"""add cash prop flag

Revision ID: c67534194872
Revises: a4a9a836db29
Create Date: 2025-11-18 22:22:41.831192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c67534194872'
down_revision: Union[str, Sequence[str], None] = 'a4a9a836db29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('is_cash_prop', sa.Boolean(create_constraint=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'is_cash_prop')
    # ### end Alembic commands ###
