"""make prop_id unique in ownership table

Revision ID: ca933ca9e956
Revises: 5e077ee666b0
Create Date: 2025-11-13 23:58:49.689319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca933ca9e956'
down_revision: Union[str, Sequence[str], None] = '5e077ee666b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'private_prop_ownership', ['prop_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'private_prop_ownership', type_='unique')
    # ### end Alembic commands ###
