"""add full text index

Revision ID: e3f00fd12fe0
Revises: 6211461fb14a
Create Date: 2025-11-14 19:42:23.776487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f00fd12fe0'
down_revision: Union[str, Sequence[str], None] = '6211461fb14a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ft_symbol_name_descp', 'property', ['symbol', 'name', 'description'], unique=False, mysql_prefix='FULLTEXT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ft_symbol_name_descp', table_name='property', mysql_prefix='FULLTEXT')
    # ### end Alembic commands ###
