"""add custom props to property

Revision ID: f1077dbbe2d5
Revises: e3f00fd12fe0
Create Date: 2025-11-14 23:11:21.414575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1077dbbe2d5'
down_revision: Union[str, Sequence[str], None] = 'e3f00fd12fe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('custom_props', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'custom_props')
    # ### end Alembic commands ###
